mkdir -p /home/adithyan/Downloads/GUMMIDIPOONDI
mkdir -p /home/adithyan/Downloads/PONNERI
mkdir -p /home/adithyan/Downloads/TIRUTTANI
mkdir -p /home/adithyan/Downloads/THIRUVALLUR
mkdir -p /home/adithyan/Downloads/POONMALLAE
mkdir -p /home/adithyan/Downloads/AVADI
mkdir -p /home/adithyan/Downloads/MADURAVOYAL
mkdir -p /home/adithyan/Downloads/AMBATTUR
mkdir -p /home/adithyan/Downloads/MADAVARAM
mkdir -p /home/adithyan/Downloads/THIRUVOTTIYUR
mkdir -p /home/adithyan/Downloads/DR_RADHAKRISHNAN_NAGAR
mkdir -p /home/adithyan/Downloads/PERAMBUR
mkdir -p /home/adithyan/Downloads/KOLATHUR
mkdir -p /home/adithyan/Downloads/VILLIVAKKAM
mkdir -p /home/adithyan/Downloads/THIRU_VI_KA_NAGAR
mkdir -p /home/adithyan/Downloads/EGMORE
mkdir -p /home/adithyan/Downloads/ROYAPURAM
mkdir -p /home/adithyan/Downloads/HARBOUR
mkdir -p /home/adithyan/Downloads/CHEPAUK_THIRUVALLIKENI
mkdir -p /home/adithyan/Downloads/THOUSAND_LIGHTS
mkdir -p /home/adithyan/Downloads/ANNA_NAGAR
mkdir -p /home/adithyan/Downloads/VIRUGAMPAKKAM
mkdir -p /home/adithyan/Downloads/SAIDAPET
mkdir -p /home/adithyan/Downloads/THIYAGARAYANAGAR
mkdir -p /home/adithyan/Downloads/MYLAPORE
mkdir -p /home/adithyan/Downloads/VELACHERY
mkdir -p /home/adithyan/Downloads/SHOZHINGANALLUR
mkdir -p /home/adithyan/Downloads/ALANDUR
mkdir -p /home/adithyan/Downloads/SRIPERUMBUDUR
mkdir -p /home/adithyan/Downloads/PALLAVARAM
mkdir -p /home/adithyan/Downloads/TAMBARAM
mkdir -p /home/adithyan/Downloads/CHENGALPATTU
mkdir -p /home/adithyan/Downloads/THIRUPORUR
mkdir -p /home/adithyan/Downloads/CHEYYUR
mkdir -p /home/adithyan/Downloads/MADURANTAKAM
mkdir -p /home/adithyan/Downloads/UTHIRAMERUR
mkdir -p /home/adithyan/Downloads/KANCHEEPURAM
mkdir -p /home/adithyan/Downloads/ARAKKONAM
mkdir -p /home/adithyan/Downloads/SHOLINGUR
mkdir -p /home/adithyan/Downloads/KATPADI
mkdir -p /home/adithyan/Downloads/RANIPET
mkdir -p /home/adithyan/Downloads/ARCOT
mkdir -p /home/adithyan/Downloads/VELLORE
mkdir -p /home/adithyan/Downloads/ANAIKATTU
mkdir -p /home/adithyan/Downloads/KILVAITHINANKUPPAM
mkdir -p /home/adithyan/Downloads/GUDIYATTAM
mkdir -p /home/adithyan/Downloads/VANIYAMBADI
mkdir -p /home/adithyan/Downloads/AMBUR
mkdir -p /home/adithyan/Downloads/JOLARPET
mkdir -p /home/adithyan/Downloads/TIRUPATTUR
mkdir -p /home/adithyan/Downloads/UTHANGARAI
mkdir -p /home/adithyan/Downloads/BARGUR
mkdir -p /home/adithyan/Downloads/KRISHNAGIRI
mkdir -p /home/adithyan/Downloads/VEPPANAHALLI
mkdir -p /home/adithyan/Downloads/HOSUR
mkdir -p /home/adithyan/Downloads/THALLI
mkdir -p /home/adithyan/Downloads/PALACODU
mkdir -p /home/adithyan/Downloads/PENNAGARAM
mkdir -p /home/adithyan/Downloads/DHARMAPURI
mkdir -p /home/adithyan/Downloads/PAPPIREDDIPPATTI
mkdir -p /home/adithyan/Downloads/HARUR
mkdir -p /home/adithyan/Downloads/CHENGAM
mkdir -p /home/adithyan/Downloads/TIRUVANNAMALAI
mkdir -p /home/adithyan/Downloads/KILPENNATHUR
mkdir -p /home/adithyan/Downloads/KALASAPAKKAM
mkdir -p /home/adithyan/Downloads/POLUR
mkdir -p /home/adithyan/Downloads/ARANI
mkdir -p /home/adithyan/Downloads/CHEYYAR
mkdir -p /home/adithyan/Downloads/VANDAVASI
mkdir -p /home/adithyan/Downloads/GINGEE
mkdir -p /home/adithyan/Downloads/MAILAM
mkdir -p /home/adithyan/Downloads/TINDIVANAM
mkdir -p /home/adithyan/Downloads/VANUR
mkdir -p /home/adithyan/Downloads/VILLUPURAM
mkdir -p /home/adithyan/Downloads/VIKRAVANDI
mkdir -p /home/adithyan/Downloads/TIRUKKOYILUR
mkdir -p /home/adithyan/Downloads/ULUNDURPETTAI
mkdir -p /home/adithyan/Downloads/RISHIVANDIYAM
mkdir -p /home/adithyan/Downloads/SANKARAPURAM
mkdir -p /home/adithyan/Downloads/KALLAKURICHI
mkdir -p /home/adithyan/Downloads/GANGAVALLI
mkdir -p /home/adithyan/Downloads/ATTUR
mkdir -p /home/adithyan/Downloads/YERCAUD
mkdir -p /home/adithyan/Downloads/OMALUR
mkdir -p /home/adithyan/Downloads/METTUR
mkdir -p /home/adithyan/Downloads/EDAPPADI
mkdir -p /home/adithyan/Downloads/SANKARI
mkdir -p /home/adithyan/Downloads/SALEM_WEST
mkdir -p /home/adithyan/Downloads/SALEM_NORTH
mkdir -p /home/adithyan/Downloads/SALEM_SOUTH
mkdir -p /home/adithyan/Downloads/VEERAPANDI
mkdir -p /home/adithyan/Downloads/RASIPURAM
mkdir -p /home/adithyan/Downloads/SENTHAMANGALAM
mkdir -p /home/adithyan/Downloads/NAMAKKAL
mkdir -p /home/adithyan/Downloads/PARAMATHI_VELUR
mkdir -p /home/adithyan/Downloads/TIRUCHENGODU
mkdir -p /home/adithyan/Downloads/KUMARAPALAYAM
mkdir -p /home/adithyan/Downloads/ERODE_EAST
mkdir -p /home/adithyan/Downloads/ERODE_WEST
mkdir -p /home/adithyan/Downloads/MODAKKURICHI
mkdir -p /home/adithyan/Downloads/DHARAPURAM
mkdir -p /home/adithyan/Downloads/KANGAYAM
mkdir -p /home/adithyan/Downloads/PERUNDURAI
mkdir -p /home/adithyan/Downloads/BHAVANI
mkdir -p /home/adithyan/Downloads/ANTHIYUR
mkdir -p /home/adithyan/Downloads/GOBICHETTIPALAYAM
mkdir -p /home/adithyan/Downloads/BHAVANISAGAR
mkdir -p /home/adithyan/Downloads/UDHAGAMANDALAM
mkdir -p /home/adithyan/Downloads/GUDALUR
mkdir -p /home/adithyan/Downloads/COONOOR
mkdir -p /home/adithyan/Downloads/METTUPPALAYAM
mkdir -p /home/adithyan/Downloads/AVANASHI
mkdir -p /home/adithyan/Downloads/TIRUPPUR_NORTH
mkdir -p /home/adithyan/Downloads/TIRUPPUR_SOUTH
mkdir -p /home/adithyan/Downloads/PALLADAM
mkdir -p /home/adithyan/Downloads/SULUR
mkdir -p /home/adithyan/Downloads/KAVUNDAMPALAYAM
mkdir -p /home/adithyan/Downloads/COIMBATORE_NORTH
mkdir -p /home/adithyan/Downloads/THONDAMUTHUR
mkdir -p /home/adithyan/Downloads/COIMBATORE_SOUTH
mkdir -p /home/adithyan/Downloads/SINGANALLUR
mkdir -p /home/adithyan/Downloads/KINATHUKADAVU
mkdir -p /home/adithyan/Downloads/POLLACHI
mkdir -p /home/adithyan/Downloads/VALPARAI
mkdir -p /home/adithyan/Downloads/UDUMALAIPETTAI
mkdir -p /home/adithyan/Downloads/MADATHUKULAM
mkdir -p /home/adithyan/Downloads/PALANI
mkdir -p /home/adithyan/Downloads/ODDANCHATRAM
mkdir -p /home/adithyan/Downloads/ATHOOR
mkdir -p /home/adithyan/Downloads/NILAKKOTTAI
mkdir -p /home/adithyan/Downloads/NATHAM
mkdir -p /home/adithyan/Downloads/DINDIGUL
mkdir -p /home/adithyan/Downloads/VEDASANDUR
mkdir -p /home/adithyan/Downloads/ARAVAKURICHI
mkdir -p /home/adithyan/Downloads/KARUR
mkdir -p /home/adithyan/Downloads/KRISHNARAYAPURAM
mkdir -p /home/adithyan/Downloads/KULITHALAI
mkdir -p /home/adithyan/Downloads/MANAPPARAI
mkdir -p /home/adithyan/Downloads/SRIRANGAM
mkdir -p /home/adithyan/Downloads/TIRUCHIRAPPALLI_WEST
mkdir -p /home/adithyan/Downloads/TIRUCHIRAPPALLI_EAST
mkdir -p /home/adithyan/Downloads/THIRUVERUMBUR
mkdir -p /home/adithyan/Downloads/LALGUDI
mkdir -p /home/adithyan/Downloads/MANACHANALLUR
mkdir -p /home/adithyan/Downloads/MUSIRI
mkdir -p /home/adithyan/Downloads/THURAIYUR
mkdir -p /home/adithyan/Downloads/PERAMBALUR
mkdir -p /home/adithyan/Downloads/KUNNAM
mkdir -p /home/adithyan/Downloads/ARIYALUR
mkdir -p /home/adithyan/Downloads/JAYANKONDAM
mkdir -p /home/adithyan/Downloads/TITTAKUDI
mkdir -p /home/adithyan/Downloads/VRIDDHACHALAM
mkdir -p /home/adithyan/Downloads/NEYVELI
mkdir -p /home/adithyan/Downloads/PANRUTI
mkdir -p /home/adithyan/Downloads/CUDDALORE
mkdir -p /home/adithyan/Downloads/KURINJIPADI
mkdir -p /home/adithyan/Downloads/BHUVANAGIRI
mkdir -p /home/adithyan/Downloads/CHIDAMBARAM
mkdir -p /home/adithyan/Downloads/KATTUMANNARKOIL
mkdir -p /home/adithyan/Downloads/SIRKAZHI
mkdir -p /home/adithyan/Downloads/MAYILADUTHURAI
mkdir -p /home/adithyan/Downloads/POOMPUHAR
mkdir -p /home/adithyan/Downloads/NAGAPATTINAM
mkdir -p /home/adithyan/Downloads/KILVELUR
mkdir -p /home/adithyan/Downloads/VEDARANYAM
mkdir -p /home/adithyan/Downloads/THIRUTHURAIPOONDI
mkdir -p /home/adithyan/Downloads/MANNARGUDI
mkdir -p /home/adithyan/Downloads/THIRUVARUR
mkdir -p /home/adithyan/Downloads/NANNILAM
mkdir -p /home/adithyan/Downloads/THIRUVIDAIMARUDUR
mkdir -p /home/adithyan/Downloads/KUMBAKONAM
mkdir -p /home/adithyan/Downloads/PAPANASAM
mkdir -p /home/adithyan/Downloads/THIRUVAIYARU
mkdir -p /home/adithyan/Downloads/THANJAVUR
mkdir -p /home/adithyan/Downloads/ORATHANADU
mkdir -p /home/adithyan/Downloads/PATTUKKOTTAI
mkdir -p /home/adithyan/Downloads/PERAVURANI
mkdir -p /home/adithyan/Downloads/GANDHARVAKOTTAI
mkdir -p /home/adithyan/Downloads/VIRALIMALAI
mkdir -p /home/adithyan/Downloads/PUDUKKOTTAI
mkdir -p /home/adithyan/Downloads/THIRUMAYAM
mkdir -p /home/adithyan/Downloads/ALANGUDI
mkdir -p /home/adithyan/Downloads/ARANTHANGI
mkdir -p /home/adithyan/Downloads/KARAIKUDI
mkdir -p /home/adithyan/Downloads/TIRUPPATTUR
mkdir -p /home/adithyan/Downloads/SIVAGANGA
mkdir -p /home/adithyan/Downloads/MANAMADURAI
mkdir -p /home/adithyan/Downloads/MELUR
mkdir -p /home/adithyan/Downloads/MADURAI_EAST
mkdir -p /home/adithyan/Downloads/SHOLAVANDAN
mkdir -p /home/adithyan/Downloads/MADURAI_NORTH
mkdir -p /home/adithyan/Downloads/MADURAI_SOUTH
mkdir -p /home/adithyan/Downloads/MADURAI_CENTRAL
mkdir -p /home/adithyan/Downloads/MADURAI_WEST
mkdir -p /home/adithyan/Downloads/THIRUPARANKUNDRAM
mkdir -p /home/adithyan/Downloads/THIRUMANGALAM
mkdir -p /home/adithyan/Downloads/USILAMPATTI
mkdir -p /home/adithyan/Downloads/ANDIPATTI
mkdir -p /home/adithyan/Downloads/PERIYAKULAM
mkdir -p /home/adithyan/Downloads/BODINAYAKANUR
mkdir -p /home/adithyan/Downloads/CUMBUM
mkdir -p /home/adithyan/Downloads/RAJAPALAYAM
mkdir -p /home/adithyan/Downloads/SRIVILLIPUTHUR
mkdir -p /home/adithyan/Downloads/SATTUR
mkdir -p /home/adithyan/Downloads/SIVAKASI
mkdir -p /home/adithyan/Downloads/VIRUDHUNAGAR
mkdir -p /home/adithyan/Downloads/ARUPPUKKOTTAI
mkdir -p /home/adithyan/Downloads/TIRUCHULI
mkdir -p /home/adithyan/Downloads/PARAMAKUDI
mkdir -p /home/adithyan/Downloads/TIRUVADANAI
mkdir -p /home/adithyan/Downloads/RAMANATHAPURAM
mkdir -p /home/adithyan/Downloads/MUDHUKULATHUR
mkdir -p /home/adithyan/Downloads/VILATHIKULAM
mkdir -p /home/adithyan/Downloads/THOOTHUKKUDI
mkdir -p /home/adithyan/Downloads/TIRUCHENDUR
mkdir -p /home/adithyan/Downloads/SRIVAIKUNTAM
mkdir -p /home/adithyan/Downloads/OTTAPIDARAM
mkdir -p /home/adithyan/Downloads/KOVILPATTI
mkdir -p /home/adithyan/Downloads/SANKARANKOVIL
mkdir -p /home/adithyan/Downloads/VASUDEVANALLUR
mkdir -p /home/adithyan/Downloads/KADAYANALLUR
mkdir -p /home/adithyan/Downloads/TENKASI
mkdir -p /home/adithyan/Downloads/ALANGULAM
mkdir -p /home/adithyan/Downloads/TIRUNELVELI
mkdir -p /home/adithyan/Downloads/AMBASAMUDRAM
mkdir -p /home/adithyan/Downloads/PALAYAMKOTTAI
mkdir -p /home/adithyan/Downloads/NANGUNERI
mkdir -p /home/adithyan/Downloads/RADHAPURAM
mkdir -p /home/adithyan/Downloads/KANNIYAKUMARI
mkdir -p /home/adithyan/Downloads/NAGERCOIL
mkdir -p /home/adithyan/Downloads/COLACHAL
mkdir -p /home/adithyan/Downloads/PADMANABHAPURAM
mkdir -p /home/adithyan/Downloads/VILAVANCODE
mkdir -p /home/adithyan/Downloads/KILLIYOOR

mv /home/adithyan/Downloads/GUMMIDIPOONDI-* /home/adithyan/Downloads/GUMMIDIPOONDI/
mv /home/adithyan/Downloads/PONNERI-* /home/adithyan/Downloads/PONNERI/
mv /home/adithyan/Downloads/TIRUTTANI-* /home/adithyan/Downloads/TIRUTTANI/
mv /home/adithyan/Downloads/THIRUVALLUR-* /home/adithyan/Downloads/THIRUVALLUR/
mv /home/adithyan/Downloads/POONMALLAE-* /home/adithyan/Downloads/POONMALLAE/
mv /home/adithyan/Downloads/AVADI-* /home/adithyan/Downloads/AVADI/
mv /home/adithyan/Downloads/MADURAVOYAL-* /home/adithyan/Downloads/MADURAVOYAL/
mv /home/adithyan/Downloads/AMBATTUR-* /home/adithyan/Downloads/AMBATTUR/
mv /home/adithyan/Downloads/MADAVARAM-* /home/adithyan/Downloads/MADAVARAM/
mv /home/adithyan/Downloads/THIRUVOTTIYUR-* /home/adithyan/Downloads/THIRUVOTTIYUR/
mv /home/adithyan/Downloads/DR_RADHAKRISHNAN_NAGAR-* /home/adithyan/Downloads/DR_RADHAKRISHNAN_NAGAR/
mv /home/adithyan/Downloads/PERAMBUR-* /home/adithyan/Downloads/PERAMBUR/
mv /home/adithyan/Downloads/KOLATHUR-* /home/adithyan/Downloads/KOLATHUR/
mv /home/adithyan/Downloads/VILLIVAKKAM-* /home/adithyan/Downloads/VILLIVAKKAM/
mv /home/adithyan/Downloads/THIRU_VI_KA_NAGAR-* /home/adithyan/Downloads/THIRU_VI_KA_NAGAR/
mv /home/adithyan/Downloads/EGMORE-* /home/adithyan/Downloads/EGMORE/
mv /home/adithyan/Downloads/ROYAPURAM-* /home/adithyan/Downloads/ROYAPURAM/
mv /home/adithyan/Downloads/HARBOUR-* /home/adithyan/Downloads/HARBOUR/
mv /home/adithyan/Downloads/CHEPAUK_THIRUVALLIKENI-* /home/adithyan/Downloads/CHEPAUK_THIRUVALLIKENI/
mv /home/adithyan/Downloads/THOUSAND_LIGHTS-* /home/adithyan/Downloads/THOUSAND_LIGHTS/
mv /home/adithyan/Downloads/ANNA_NAGAR-* /home/adithyan/Downloads/ANNA_NAGAR/
mv /home/adithyan/Downloads/VIRUGAMPAKKAM-* /home/adithyan/Downloads/VIRUGAMPAKKAM/
mv /home/adithyan/Downloads/SAIDAPET-* /home/adithyan/Downloads/SAIDAPET/
mv /home/adithyan/Downloads/THIYAGARAYANAGAR-* /home/adithyan/Downloads/THIYAGARAYANAGAR/
mv /home/adithyan/Downloads/MYLAPORE-* /home/adithyan/Downloads/MYLAPORE/
mv /home/adithyan/Downloads/VELACHERY-* /home/adithyan/Downloads/VELACHERY/
mv /home/adithyan/Downloads/SHOZHINGANALLUR-* /home/adithyan/Downloads/SHOZHINGANALLUR/
mv /home/adithyan/Downloads/ALANDUR-* /home/adithyan/Downloads/ALANDUR/
mv /home/adithyan/Downloads/SRIPERUMBUDUR-* /home/adithyan/Downloads/SRIPERUMBUDUR/
mv /home/adithyan/Downloads/PALLAVARAM-* /home/adithyan/Downloads/PALLAVARAM/
mv /home/adithyan/Downloads/TAMBARAM-* /home/adithyan/Downloads/TAMBARAM/
mv /home/adithyan/Downloads/CHENGALPATTU-* /home/adithyan/Downloads/CHENGALPATTU/
mv /home/adithyan/Downloads/THIRUPORUR-* /home/adithyan/Downloads/THIRUPORUR/
mv /home/adithyan/Downloads/CHEYYUR-* /home/adithyan/Downloads/CHEYYUR/
mv /home/adithyan/Downloads/MADURANTAKAM-* /home/adithyan/Downloads/MADURANTAKAM/
mv /home/adithyan/Downloads/UTHIRAMERUR-* /home/adithyan/Downloads/UTHIRAMERUR/
mv /home/adithyan/Downloads/KANCHEEPURAM-* /home/adithyan/Downloads/KANCHEEPURAM/
mv /home/adithyan/Downloads/ARAKKONAM-* /home/adithyan/Downloads/ARAKKONAM/
mv /home/adithyan/Downloads/SHOLINGUR-* /home/adithyan/Downloads/SHOLINGUR/
mv /home/adithyan/Downloads/KATPADI-* /home/adithyan/Downloads/KATPADI/
mv /home/adithyan/Downloads/RANIPET-* /home/adithyan/Downloads/RANIPET/
mv /home/adithyan/Downloads/ARCOT-* /home/adithyan/Downloads/ARCOT/
mv /home/adithyan/Downloads/VELLORE-* /home/adithyan/Downloads/VELLORE/
mv /home/adithyan/Downloads/ANAIKATTU-* /home/adithyan/Downloads/ANAIKATTU/
mv /home/adithyan/Downloads/KILVAITHINANKUPPAM-* /home/adithyan/Downloads/KILVAITHINANKUPPAM/
mv /home/adithyan/Downloads/GUDIYATTAM-* /home/adithyan/Downloads/GUDIYATTAM/
mv /home/adithyan/Downloads/VANIYAMBADI-* /home/adithyan/Downloads/VANIYAMBADI/
mv /home/adithyan/Downloads/AMBUR-* /home/adithyan/Downloads/AMBUR/
mv /home/adithyan/Downloads/JOLARPET-* /home/adithyan/Downloads/JOLARPET/
mv /home/adithyan/Downloads/TIRUPATTUR-* /home/adithyan/Downloads/TIRUPATTUR/
mv /home/adithyan/Downloads/UTHANGARAI-* /home/adithyan/Downloads/UTHANGARAI/
mv /home/adithyan/Downloads/BARGUR-* /home/adithyan/Downloads/BARGUR/
mv /home/adithyan/Downloads/KRISHNAGIRI-* /home/adithyan/Downloads/KRISHNAGIRI/
mv /home/adithyan/Downloads/VEPPANAHALLI-* /home/adithyan/Downloads/VEPPANAHALLI/
mv /home/adithyan/Downloads/HOSUR-* /home/adithyan/Downloads/HOSUR/
mv /home/adithyan/Downloads/THALLI-* /home/adithyan/Downloads/THALLI/
mv /home/adithyan/Downloads/PALACODU-* /home/adithyan/Downloads/PALACODU/
mv /home/adithyan/Downloads/PENNAGARAM-* /home/adithyan/Downloads/PENNAGARAM/
mv /home/adithyan/Downloads/DHARMAPURI-* /home/adithyan/Downloads/DHARMAPURI/
mv /home/adithyan/Downloads/PAPPIREDDIPPATTI-* /home/adithyan/Downloads/PAPPIREDDIPPATTI/
mv /home/adithyan/Downloads/HARUR-* /home/adithyan/Downloads/HARUR/
mv /home/adithyan/Downloads/CHENGAM-* /home/adithyan/Downloads/CHENGAM/
mv /home/adithyan/Downloads/TIRUVANNAMALAI-* /home/adithyan/Downloads/TIRUVANNAMALAI/
mv /home/adithyan/Downloads/KILPENNATHUR-* /home/adithyan/Downloads/KILPENNATHUR/
mv /home/adithyan/Downloads/KALASAPAKKAM-* /home/adithyan/Downloads/KALASAPAKKAM/
mv /home/adithyan/Downloads/POLUR-* /home/adithyan/Downloads/POLUR/
mv /home/adithyan/Downloads/ARANI-* /home/adithyan/Downloads/ARANI/
mv /home/adithyan/Downloads/CHEYYAR-* /home/adithyan/Downloads/CHEYYAR/
mv /home/adithyan/Downloads/VANDAVASI-* /home/adithyan/Downloads/VANDAVASI/
mv /home/adithyan/Downloads/GINGEE-* /home/adithyan/Downloads/GINGEE/
mv /home/adithyan/Downloads/MAILAM-* /home/adithyan/Downloads/MAILAM/
mv /home/adithyan/Downloads/TINDIVANAM-* /home/adithyan/Downloads/TINDIVANAM/
mv /home/adithyan/Downloads/VANUR-* /home/adithyan/Downloads/VANUR/
mv /home/adithyan/Downloads/VILLUPURAM-* /home/adithyan/Downloads/VILLUPURAM/
mv /home/adithyan/Downloads/VIKRAVANDI-* /home/adithyan/Downloads/VIKRAVANDI/
mv /home/adithyan/Downloads/TIRUKKOYILUR-* /home/adithyan/Downloads/TIRUKKOYILUR/
mv /home/adithyan/Downloads/ULUNDURPETTAI-* /home/adithyan/Downloads/ULUNDURPETTAI/
mv /home/adithyan/Downloads/RISHIVANDIYAM-* /home/adithyan/Downloads/RISHIVANDIYAM/
mv /home/adithyan/Downloads/SANKARAPURAM-* /home/adithyan/Downloads/SANKARAPURAM/
mv /home/adithyan/Downloads/KALLAKURICHI-* /home/adithyan/Downloads/KALLAKURICHI/
mv /home/adithyan/Downloads/GANGAVALLI-* /home/adithyan/Downloads/GANGAVALLI/
mv /home/adithyan/Downloads/ATTUR-* /home/adithyan/Downloads/ATTUR/
mv /home/adithyan/Downloads/YERCAUD-* /home/adithyan/Downloads/YERCAUD/
mv /home/adithyan/Downloads/OMALUR-* /home/adithyan/Downloads/OMALUR/
mv /home/adithyan/Downloads/METTUR-* /home/adithyan/Downloads/METTUR/
mv /home/adithyan/Downloads/EDAPPADI-* /home/adithyan/Downloads/EDAPPADI/
mv /home/adithyan/Downloads/SANKARI-* /home/adithyan/Downloads/SANKARI/
mv /home/adithyan/Downloads/SALEM_WEST-* /home/adithyan/Downloads/SALEM_WEST/
mv /home/adithyan/Downloads/SALEM_NORTH-* /home/adithyan/Downloads/SALEM_NORTH/
mv /home/adithyan/Downloads/SALEM_SOUTH-* /home/adithyan/Downloads/SALEM_SOUTH/
mv /home/adithyan/Downloads/VEERAPANDI-* /home/adithyan/Downloads/VEERAPANDI/
mv /home/adithyan/Downloads/RASIPURAM-* /home/adithyan/Downloads/RASIPURAM/
mv /home/adithyan/Downloads/SENTHAMANGALAM-* /home/adithyan/Downloads/SENTHAMANGALAM/
mv /home/adithyan/Downloads/NAMAKKAL-* /home/adithyan/Downloads/NAMAKKAL/
mv /home/adithyan/Downloads/PARAMATHI_VELUR-* /home/adithyan/Downloads/PARAMATHI_VELUR/
mv /home/adithyan/Downloads/TIRUCHENGODU-* /home/adithyan/Downloads/TIRUCHENGODU/
mv /home/adithyan/Downloads/KUMARAPALAYAM-* /home/adithyan/Downloads/KUMARAPALAYAM/
mv /home/adithyan/Downloads/ERODE_EAST-* /home/adithyan/Downloads/ERODE_EAST/
mv /home/adithyan/Downloads/ERODE_WEST-* /home/adithyan/Downloads/ERODE_WEST/
mv /home/adithyan/Downloads/MODAKKURICHI-* /home/adithyan/Downloads/MODAKKURICHI/
mv /home/adithyan/Downloads/DHARAPURAM-* /home/adithyan/Downloads/DHARAPURAM/
mv /home/adithyan/Downloads/KANGAYAM-* /home/adithyan/Downloads/KANGAYAM/
mv /home/adithyan/Downloads/PERUNDURAI-* /home/adithyan/Downloads/PERUNDURAI/
mv /home/adithyan/Downloads/BHAVANI-* /home/adithyan/Downloads/BHAVANI/
mv /home/adithyan/Downloads/ANTHIYUR-* /home/adithyan/Downloads/ANTHIYUR/
mv /home/adithyan/Downloads/GOBICHETTIPALAYAM-* /home/adithyan/Downloads/GOBICHETTIPALAYAM/
mv /home/adithyan/Downloads/BHAVANISAGAR-* /home/adithyan/Downloads/BHAVANISAGAR/
mv /home/adithyan/Downloads/UDHAGAMANDALAM-* /home/adithyan/Downloads/UDHAGAMANDALAM/
mv /home/adithyan/Downloads/GUDALUR-* /home/adithyan/Downloads/GUDALUR/
mv /home/adithyan/Downloads/COONOOR-* /home/adithyan/Downloads/COONOOR/
mv /home/adithyan/Downloads/METTUPPALAYAM-* /home/adithyan/Downloads/METTUPPALAYAM/
mv /home/adithyan/Downloads/AVANASHI-* /home/adithyan/Downloads/AVANASHI/
mv /home/adithyan/Downloads/TIRUPPUR_NORTH-* /home/adithyan/Downloads/TIRUPPUR_NORTH/
mv /home/adithyan/Downloads/TIRUPPUR_SOUTH-* /home/adithyan/Downloads/TIRUPPUR_SOUTH/
mv /home/adithyan/Downloads/PALLADAM-* /home/adithyan/Downloads/PALLADAM/
mv /home/adithyan/Downloads/SULUR-* /home/adithyan/Downloads/SULUR/
mv /home/adithyan/Downloads/KAVUNDAMPALAYAM-* /home/adithyan/Downloads/KAVUNDAMPALAYAM/
mv /home/adithyan/Downloads/COIMBATORE_NORTH-* /home/adithyan/Downloads/COIMBATORE_NORTH/
mv /home/adithyan/Downloads/THONDAMUTHUR-* /home/adithyan/Downloads/THONDAMUTHUR/
mv /home/adithyan/Downloads/COIMBATORE_SOUTH-* /home/adithyan/Downloads/COIMBATORE_SOUTH/
mv /home/adithyan/Downloads/SINGANALLUR-* /home/adithyan/Downloads/SINGANALLUR/
mv /home/adithyan/Downloads/KINATHUKADAVU-* /home/adithyan/Downloads/KINATHUKADAVU/
mv /home/adithyan/Downloads/POLLACHI-* /home/adithyan/Downloads/POLLACHI/
mv /home/adithyan/Downloads/VALPARAI-* /home/adithyan/Downloads/VALPARAI/
mv /home/adithyan/Downloads/UDUMALAIPETTAI-* /home/adithyan/Downloads/UDUMALAIPETTAI/
mv /home/adithyan/Downloads/MADATHUKULAM-* /home/adithyan/Downloads/MADATHUKULAM/
mv /home/adithyan/Downloads/PALANI-* /home/adithyan/Downloads/PALANI/
mv /home/adithyan/Downloads/ODDANCHATRAM-* /home/adithyan/Downloads/ODDANCHATRAM/
mv /home/adithyan/Downloads/ATHOOR-* /home/adithyan/Downloads/ATHOOR/
mv /home/adithyan/Downloads/NILAKKOTTAI-* /home/adithyan/Downloads/NILAKKOTTAI/
mv /home/adithyan/Downloads/NATHAM-* /home/adithyan/Downloads/NATHAM/
mv /home/adithyan/Downloads/DINDIGUL-* /home/adithyan/Downloads/DINDIGUL/
mv /home/adithyan/Downloads/VEDASANDUR-* /home/adithyan/Downloads/VEDASANDUR/
mv /home/adithyan/Downloads/ARAVAKURICHI-* /home/adithyan/Downloads/ARAVAKURICHI/
mv /home/adithyan/Downloads/KARUR-* /home/adithyan/Downloads/KARUR/
mv /home/adithyan/Downloads/KRISHNARAYAPURAM-* /home/adithyan/Downloads/KRISHNARAYAPURAM/
mv /home/adithyan/Downloads/KULITHALAI-* /home/adithyan/Downloads/KULITHALAI/
mv /home/adithyan/Downloads/MANAPPARAI-* /home/adithyan/Downloads/MANAPPARAI/
mv /home/adithyan/Downloads/SRIRANGAM-* /home/adithyan/Downloads/SRIRANGAM/
mv /home/adithyan/Downloads/TIRUCHIRAPPALLI_WEST-* /home/adithyan/Downloads/TIRUCHIRAPPALLI_WEST/
mv /home/adithyan/Downloads/TIRUCHIRAPPALLI_EAST-* /home/adithyan/Downloads/TIRUCHIRAPPALLI_EAST/
mv /home/adithyan/Downloads/THIRUVERUMBUR-* /home/adithyan/Downloads/THIRUVERUMBUR/
mv /home/adithyan/Downloads/LALGUDI-* /home/adithyan/Downloads/LALGUDI/
mv /home/adithyan/Downloads/MANACHANALLUR-* /home/adithyan/Downloads/MANACHANALLUR/
mv /home/adithyan/Downloads/MUSIRI-* /home/adithyan/Downloads/MUSIRI/
mv /home/adithyan/Downloads/THURAIYUR-* /home/adithyan/Downloads/THURAIYUR/
mv /home/adithyan/Downloads/PERAMBALUR-* /home/adithyan/Downloads/PERAMBALUR/
mv /home/adithyan/Downloads/KUNNAM-* /home/adithyan/Downloads/KUNNAM/
mv /home/adithyan/Downloads/ARIYALUR-* /home/adithyan/Downloads/ARIYALUR/
mv /home/adithyan/Downloads/JAYANKONDAM-* /home/adithyan/Downloads/JAYANKONDAM/
mv /home/adithyan/Downloads/TITTAKUDI-* /home/adithyan/Downloads/TITTAKUDI/
mv /home/adithyan/Downloads/VRIDDHACHALAM-* /home/adithyan/Downloads/VRIDDHACHALAM/
mv /home/adithyan/Downloads/NEYVELI-* /home/adithyan/Downloads/NEYVELI/
mv /home/adithyan/Downloads/PANRUTI-* /home/adithyan/Downloads/PANRUTI/
mv /home/adithyan/Downloads/CUDDALORE-* /home/adithyan/Downloads/CUDDALORE/
mv /home/adithyan/Downloads/KURINJIPADI-* /home/adithyan/Downloads/KURINJIPADI/
mv /home/adithyan/Downloads/BHUVANAGIRI-* /home/adithyan/Downloads/BHUVANAGIRI/
mv /home/adithyan/Downloads/CHIDAMBARAM-* /home/adithyan/Downloads/CHIDAMBARAM/
mv /home/adithyan/Downloads/KATTUMANNARKOIL-* /home/adithyan/Downloads/KATTUMANNARKOIL/
mv /home/adithyan/Downloads/SIRKAZHI-* /home/adithyan/Downloads/SIRKAZHI/
mv /home/adithyan/Downloads/MAYILADUTHURAI-* /home/adithyan/Downloads/MAYILADUTHURAI/
mv /home/adithyan/Downloads/POOMPUHAR-* /home/adithyan/Downloads/POOMPUHAR/
mv /home/adithyan/Downloads/NAGAPATTINAM-* /home/adithyan/Downloads/NAGAPATTINAM/
mv /home/adithyan/Downloads/KILVELUR-* /home/adithyan/Downloads/KILVELUR/
mv /home/adithyan/Downloads/VEDARANYAM-* /home/adithyan/Downloads/VEDARANYAM/
mv /home/adithyan/Downloads/THIRUTHURAIPOONDI-* /home/adithyan/Downloads/THIRUTHURAIPOONDI/
mv /home/adithyan/Downloads/MANNARGUDI-* /home/adithyan/Downloads/MANNARGUDI/
mv /home/adithyan/Downloads/THIRUVARUR-* /home/adithyan/Downloads/THIRUVARUR/
mv /home/adithyan/Downloads/NANNILAM-* /home/adithyan/Downloads/NANNILAM/
mv /home/adithyan/Downloads/THIRUVIDAIMARUDUR-* /home/adithyan/Downloads/THIRUVIDAIMARUDUR/
mv /home/adithyan/Downloads/KUMBAKONAM-* /home/adithyan/Downloads/KUMBAKONAM/
mv /home/adithyan/Downloads/PAPANASAM-* /home/adithyan/Downloads/PAPANASAM/
mv /home/adithyan/Downloads/THIRUVAIYARU-* /home/adithyan/Downloads/THIRUVAIYARU/
mv /home/adithyan/Downloads/THANJAVUR-* /home/adithyan/Downloads/THANJAVUR/
mv /home/adithyan/Downloads/ORATHANADU-* /home/adithyan/Downloads/ORATHANADU/
mv /home/adithyan/Downloads/PATTUKKOTTAI-* /home/adithyan/Downloads/PATTUKKOTTAI/
mv /home/adithyan/Downloads/PERAVURANI-* /home/adithyan/Downloads/PERAVURANI/
mv /home/adithyan/Downloads/GANDHARVAKOTTAI-* /home/adithyan/Downloads/GANDHARVAKOTTAI/
mv /home/adithyan/Downloads/VIRALIMALAI-* /home/adithyan/Downloads/VIRALIMALAI/
mv /home/adithyan/Downloads/PUDUKKOTTAI-* /home/adithyan/Downloads/PUDUKKOTTAI/
mv /home/adithyan/Downloads/THIRUMAYAM-* /home/adithyan/Downloads/THIRUMAYAM/
mv /home/adithyan/Downloads/ALANGUDI-* /home/adithyan/Downloads/ALANGUDI/
mv /home/adithyan/Downloads/ARANTHANGI-* /home/adithyan/Downloads/ARANTHANGI/
mv /home/adithyan/Downloads/KARAIKUDI-* /home/adithyan/Downloads/KARAIKUDI/
mv /home/adithyan/Downloads/TIRUPPATTUR-* /home/adithyan/Downloads/TIRUPPATTUR/
mv /home/adithyan/Downloads/SIVAGANGA-* /home/adithyan/Downloads/SIVAGANGA/
mv /home/adithyan/Downloads/MANAMADURAI-* /home/adithyan/Downloads/MANAMADURAI/
mv /home/adithyan/Downloads/MELUR-* /home/adithyan/Downloads/MELUR/
mv /home/adithyan/Downloads/MADURAI_EAST-* /home/adithyan/Downloads/MADURAI_EAST/
mv /home/adithyan/Downloads/SHOLAVANDAN-* /home/adithyan/Downloads/SHOLAVANDAN/
mv /home/adithyan/Downloads/MADURAI_NORTH-* /home/adithyan/Downloads/MADURAI_NORTH/
mv /home/adithyan/Downloads/MADURAI_SOUTH-* /home/adithyan/Downloads/MADURAI_SOUTH/
mv /home/adithyan/Downloads/MADURAI_CENTRAL-* /home/adithyan/Downloads/MADURAI_CENTRAL/
mv /home/adithyan/Downloads/MADURAI_WEST-* /home/adithyan/Downloads/MADURAI_WEST/
mv /home/adithyan/Downloads/THIRUPARANKUNDRAM-* /home/adithyan/Downloads/THIRUPARANKUNDRAM/
mv /home/adithyan/Downloads/THIRUMANGALAM-* /home/adithyan/Downloads/THIRUMANGALAM/
mv /home/adithyan/Downloads/USILAMPATTI-* /home/adithyan/Downloads/USILAMPATTI/
mv /home/adithyan/Downloads/ANDIPATTI-* /home/adithyan/Downloads/ANDIPATTI/
mv /home/adithyan/Downloads/PERIYAKULAM-* /home/adithyan/Downloads/PERIYAKULAM/
mv /home/adithyan/Downloads/BODINAYAKANUR-* /home/adithyan/Downloads/BODINAYAKANUR/
mv /home/adithyan/Downloads/CUMBUM-* /home/adithyan/Downloads/CUMBUM/
mv /home/adithyan/Downloads/RAJAPALAYAM-* /home/adithyan/Downloads/RAJAPALAYAM/
mv /home/adithyan/Downloads/SRIVILLIPUTHUR-* /home/adithyan/Downloads/SRIVILLIPUTHUR/
mv /home/adithyan/Downloads/SATTUR-* /home/adithyan/Downloads/SATTUR/
mv /home/adithyan/Downloads/SIVAKASI-* /home/adithyan/Downloads/SIVAKASI/
mv /home/adithyan/Downloads/VIRUDHUNAGAR-* /home/adithyan/Downloads/VIRUDHUNAGAR/
mv /home/adithyan/Downloads/ARUPPUKKOTTAI-* /home/adithyan/Downloads/ARUPPUKKOTTAI/
mv /home/adithyan/Downloads/TIRUCHULI-* /home/adithyan/Downloads/TIRUCHULI/
mv /home/adithyan/Downloads/PARAMAKUDI-* /home/adithyan/Downloads/PARAMAKUDI/
mv /home/adithyan/Downloads/TIRUVADANAI-* /home/adithyan/Downloads/TIRUVADANAI/
mv /home/adithyan/Downloads/RAMANATHAPURAM-* /home/adithyan/Downloads/RAMANATHAPURAM/
mv /home/adithyan/Downloads/MUDHUKULATHUR-* /home/adithyan/Downloads/MUDHUKULATHUR/
mv /home/adithyan/Downloads/VILATHIKULAM-* /home/adithyan/Downloads/VILATHIKULAM/
mv /home/adithyan/Downloads/THOOTHUKKUDI-* /home/adithyan/Downloads/THOOTHUKKUDI/
mv /home/adithyan/Downloads/TIRUCHENDUR-* /home/adithyan/Downloads/TIRUCHENDUR/
mv /home/adithyan/Downloads/SRIVAIKUNTAM-* /home/adithyan/Downloads/SRIVAIKUNTAM/
mv /home/adithyan/Downloads/OTTAPIDARAM-* /home/adithyan/Downloads/OTTAPIDARAM/
mv /home/adithyan/Downloads/KOVILPATTI-* /home/adithyan/Downloads/KOVILPATTI/
mv /home/adithyan/Downloads/SANKARANKOVIL-* /home/adithyan/Downloads/SANKARANKOVIL/
mv /home/adithyan/Downloads/VASUDEVANALLUR-* /home/adithyan/Downloads/VASUDEVANALLUR/
mv /home/adithyan/Downloads/KADAYANALLUR-* /home/adithyan/Downloads/KADAYANALLUR/
mv /home/adithyan/Downloads/TENKASI-* /home/adithyan/Downloads/TENKASI/
mv /home/adithyan/Downloads/ALANGULAM-* /home/adithyan/Downloads/ALANGULAM/
mv /home/adithyan/Downloads/TIRUNELVELI-* /home/adithyan/Downloads/TIRUNELVELI/
mv /home/adithyan/Downloads/AMBASAMUDRAM-* /home/adithyan/Downloads/AMBASAMUDRAM/
mv /home/adithyan/Downloads/PALAYAMKOTTAI-* /home/adithyan/Downloads/PALAYAMKOTTAI/
mv /home/adithyan/Downloads/NANGUNERI-* /home/adithyan/Downloads/NANGUNERI/
mv /home/adithyan/Downloads/RADHAPURAM-* /home/adithyan/Downloads/RADHAPURAM/
mv /home/adithyan/Downloads/KANNIYAKUMARI-* /home/adithyan/Downloads/KANNIYAKUMARI/
mv /home/adithyan/Downloads/NAGERCOIL-* /home/adithyan/Downloads/NAGERCOIL/
mv /home/adithyan/Downloads/COLACHAL-* /home/adithyan/Downloads/COLACHAL/
mv /home/adithyan/Downloads/PADMANABHAPURAM-* /home/adithyan/Downloads/PADMANABHAPURAM/
mv /home/adithyan/Downloads/VILAVANCODE-* /home/adithyan/Downloads/VILAVANCODE/
mv /home/adithyan/Downloads/KILLIYOOR-* /home/adithyan/Downloads/KILLIYOOR/
